/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.5.1/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building a CLI application
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    // This dependency is used by the application.
    implementation("com.slack.api:bolt:1.0.1")
    implementation("com.slack.api:bolt-servlet:1.0.1")
    implementation("com.slack.api:bolt-jetty:1.0.1")
    implementation("com.slack.api:slack-api-client:1.0.1")
    implementation("org.slf4j:slf4j-simple:1.7.30")

    // Use JUnit test framework
    testImplementation("junit:junit:4.12")
}

application {
    val SLACK_BOT_TOKEN: String by project
    val SLACK_SIGNING_SECRET: String by project

    // Define the main class for the application
    mainClassName = "com.metaui.edgebot.EdgeBotMain"
    applicationDefaultJvmArgs = listOf(
            "-Dorg.eclipse.jetty.LEVEL=DEBUG",
            "-DSLACK_BOT_TOKEN=$SLACK_BOT_TOKEN",
            "-DSLACK_SIGNING_SECRET=$SLACK_SIGNING_SECRET"
    )
}

//run {
//    systemProperty "org.slf4j.simpleLogger.log.com.slack.api", System.getProperty("slackLogLevel")
//}