/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.metaui.edgebot;

import org.junit.Test;
import static org.junit.Assert.*;

public class EdgeBotTest {
    @Test public void testAppHasAGreeting() {
        EdgeBot classUnderTest = new EdgeBot();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
