/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.metaui.edgebot;

import org.junit.Test;

public class EdgeBotTest {
    @Test public void testAppHasAGreeting() {
        EdgeBotMain classUnderTest = new EdgeBotMain();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
